targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - "lib/**/data/dto/*.dart"
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/**/presentation/*.dart
      auto_route_generator:auto_router_generator:
        generate_for:
          - lib/router/*.dart