name: two_piece_store_web_app
description: TwoPiece Store WebApp
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  ant_design_flutter: ^0.0.1+5
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cloud_firestore: ^4.13.6
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  js: ^0.6.7
  json_annotation: ^4.8.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
        - asset: fonts/Roboto-ThinItalic.ttf
        - asset: fonts/Roboto-Light.ttf
        - asset: fonts/Roboto-LightItalic.ttf
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Italic.ttf
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-MediumItalic.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-BoldItalic.ttf
        - asset: fonts/Roboto-Black.ttf
        - asset: fonts/Roboto-BlackItalic.ttf
